{% set name = "tf2onnx" %}
{% set version = "1.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/onnx/tensorflow-onnx/archive/v{{ version }}.tar.gz
  sha256: 3abeb0014563b93f12bb39e403d8c08b68fc421589e8c46f450cb828d4aa6d07

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - python
    - pip
    - pytest-runner
    - numpy
    - onnx >=1.4.1
    - requests
    - six 1.15
  run:
    - python
    - onnx >=1.4.1
    - {{ pin_compatible('numpy') }}
    - six 1.15
    - typing-extensions 3.7.4
    - requests
    - python-flatbuffers 1.12
    - tensorflow >=1.5

test:
  requires:
    - pip
  commands:
    - pip check
    - python -m tf2onnx.convert --help

about:
  home: https://github.com/onnx/tensorflow-onnx
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tensorflow to ONNX converter
  description: tf2onnx - convert TensorFlow models to ONNX models.
  doc_url: http://simplejson.readthedocs.io/
  dev_url: https://github.com/onnx/tensorflow-onnx

extra:
  recipe-maintainers:
    - marcelotrevisani
    - xhochy
