{% set name = "tf2onnx" %}
{% set version = "1.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/onnx/tensorflow-onnx/archive/v{{ version }}.tar.gz
  sha256: 3eb7c706b394b9e6b4074fc626369e2876400fd34a9256b00753216014081093

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: true    # [win or py>=37 or py2k]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - pytest-runner
    - numpy >=1.14.1
    - onnx >=1.4.1
    - requests
    - six
    - setuptools
  run:
    - python
    - tensorflow >=1.5.0
    - onnx >=1.4.1
    - {{ pin_compatible('numpy') }}
    - six
    - protobuf
    - requests
    - attrs

test:
  commands:
    - python -m tf2onnx.convert --help

about:
  home: https://github.com/onnx/tensorflow-onnx
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Tensorflow to ONNX converter'
  description: 'tf2onnx - convert TensorFlow models to ONNX models.'
  doc_url: http://simplejson.readthedocs.io/
  dev_url: https://github.com/onnx/tensorflow-onnx

extra:
  recipe-maintainers:
    - marcelotrevisani
