{% set name = "tf2onnx" %}
{% set version = "1.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/onnx/tensorflow-onnx/archive/v{{ version }}.tar.gz
  sha256: 133c3c28a761bc3b2307081920268f4c246d89cce35f50ba8018e105995f8d28

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win or py>=37 or py2k]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - pytest-runner
    - numpy >=1.14.1
    - onnx >=1.4.1
    - requests
    - six
    - setuptools
  run:
    - python
    - tensorflow >=1.5.0
    - onnx >=1.4.1
    - {{ pin_compatible('numpy') }}
    - six
    - protobuf
    - requests
    - attrs

test:
  commands:
    - python -m tf2onnx.convert --help

about:
  home: https://github.com/onnx/tensorflow-onnx
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tensorflow to ONNX converter
  description: tf2onnx - convert TensorFlow models to ONNX models.
  doc_url: http://simplejson.readthedocs.io/
  dev_url: https://github.com/onnx/tensorflow-onnx

extra:
  recipe-maintainers:
    - marcelotrevisani
