{% set name = "tf2onnx" %}
{% set version = "1.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/onnx/tensorflow-onnx/archive/v{{ version }}.tar.gz
  sha256: 53797ea40cd3ef31649a539a0abcb23d5250026fd12607ac3d86c262e049dbd9

build:
  number: 1
  script:
    # We will manage the build time requirements in conda
    # In 2023/09/17 they had a frivolous constrainst on pytest-runner at build time
    - sed -i "/setup_requires=/d" setup.py
    # We will manage our own constraints for protobuf in conda
    - sed -i "s/'protobuf.*'/'protobuf'/g" setup.py
    - {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - onnx >=1.4.1
    - numpy >=1.14.1
    - six
    - requests
    - python-flatbuffers >=1.12
    - tensorflow >=2.6

test:
  requires:
    - pip
  commands:
    - pip check
    - python -m tf2onnx.convert --help

about:
  home: https://github.com/onnx/tensorflow-onnx
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tensorflow to ONNX converter
  description: tf2onnx - convert TensorFlow models to ONNX models.
  doc_url: http://simplejson.readthedocs.io/
  dev_url: https://github.com/onnx/tensorflow-onnx

extra:
  recipe-maintainers:
    - marcelotrevisani
    - xhochy
